[config]
reload_apps = true

[templates.hyprland]
input_path = "./templates/hyprland.conf"
output_path = "/home/ensomnatt/.config/hypr/colors.conf"

[templates.rofi]
input_path = "./templates/rofi.conf"
output_path = "/home/ensomnatt/.config/rofi/colors.rasi"

[templates.waybar]
input_path = "./templates/colors.css"
output_path = "/home/ensomnatt/waybar/colors.css"

[templates.dunst]
input_path = "./templates/dunstrc"
output_path = "/home/ensomnatt/.config/dunst/dunstrc"
pre_hook = "pkill dunst"
post_hook = "dunst &"

[templates.wezterm]
input_path = "./templates/wezterm.hbs"
output_path = "/home/ensomnatt/.config/wezterm/colors.lua"

[templates.wlogout]
input_path = "./templates/colors.css"
output_path = "/home/ensomnatt/.config/wlogout/colors.css"
