[config]
reload_apps = true

[templates.hyprland]
input_path = "/home/ensomnatt/nixos/modules/nixos/config/matugen/templates/hyprland.conf"
output_path = "/home/ensomnatt/.config/hypr/colors.conf"

[templates.rofi]
input_path = "/home/ensomnatt/nixos/modules/nixos/config/matugen/templates/rofi.rasi"
output_path = "/home/ensomnatt/.config/rofi/matugen.rasi"

[templates.waybar]
input_path = "/home/ensomnatt/nixos/modules/nixos/config/matugen/templates/colors.css"
output_path = "/home/ensomnatt/.config/waybar/colors.css"

[templates.dunst]
input_path = "/home/ensomnatt/nixos/modules/nixos/config/matugen/templates/dunstrc"
output_path = "/home/ensomnatt/.config/dunst/dunstrc"
# pre_hook = "pkill dunst"
# post_hook = "dunst &"

[templates.wezterm]
input_path = "/home/ensomnatt/nixos/modules/nixos/config/matugen/templates/wezterm.hbs"
output_path = "/home/ensomnatt/.config/wezterm/colors.lua"

[templates.wlogout]
input_path = "/home/ensomnatt/nixos/modules/nixos/config/matugen/templates/colors.css"
output_path = "/home/ensomnatt/.config/wlogout/colors.css"
